version: "3.8"
services:
  bike-rent-express:
    build: .
    env_file:
      - .Env
    ports:
      - "8080:8080"
    networks:
      - bike_rent_express_net
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DATABASE=db-bike-rent-express
    volumes:
      - bike-rent-express-volume:/var/lib/postgresql/data
    networks:
      - bike_rent_express_net
volumes:
  bike-rent-express-volume:
networks:
  bike_rent_express_net:
    driver: bridge
